/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_gdx_physics_box2d_collision_Collision */

#ifndef _Included_com_badlogic_gdx_physics_box2d_collision_Collision
#define _Included_com_badlogic_gdx_physics_box2d_collision_Collision
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogic_gdx_physics_box2d_collision_Collision
 * Method:    jniGetPointStates
 * Signature: ([I[IJJ)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_physics_box2d_collision_Collision_jniGetPointStates
  (JNIEnv *, jobject, jintArray, jintArray, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
